version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  gateway:
    build:
      context: ./server/gateway
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - server/.env
    depends_on:
      db:
        condition: service_healthy

  likes:
    build:
      context: ./server/likes
      dockerfile: Dockerfile
    env_file:
      - server/.env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  matching:
    build:
      context: ./server/matching
      dockerfile: Dockerfile
    env_file:
      - server/.env
    depends_on:
      db:
        condition: service_healthy

  profiles:
    build:
      context: ./server/profiles
      dockerfile: Dockerfile
    env_file:
      - server/.env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure