# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x05proto\"g\n\x07Profile\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x0e\n\x06pfp_id\x18\x06 \x01(\t\".\n\x04Like\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x15\n\rliked_user_id\x18\x02 \x01(\x03\"1\n\x0eProfileRequest\x12\x1f\n\x07profile\x18\x01 \x01(\x0b\x32\x0e.proto.Profile\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"*\n\rTargetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05tgtId\x18\x02 \x01(\x03\"&\n\rErrorResponse\x12\x15\n\rerror_message\x18\x01 \x01(\t\"+\n\rLikesResponse\x12\x1a\n\x05likes\x18\x01 \x03(\x0b\x32\x0b.proto.Like\"\x07\n\x05\x45mpty2\xd5\x02\n\x0eProfileService\x12<\n\rCreateProfile\x12\x15.proto.ProfileRequest\x1a\x14.proto.ErrorResponse\x12/\n\x0bReadProfile\x12\x10.proto.IdRequest\x1a\x0e.proto.Profile\x12<\n\rUpdateProfile\x12\x15.proto.ProfileRequest\x1a\x14.proto.ErrorResponse\x12\x32\n\x0eGetNextProfile\x12\x10.proto.IdRequest\x1a\x0e.proto.Profile\x12\x32\n\x04Like\x12\x14.proto.TargetRequest\x1a\x14.proto.ErrorResponse\x12.\n\x08GetLikes\x12\x0c.proto.Empty\x1a\x14.proto.LikesResponseB\x11Z\x0f\x64p_mock/profileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017dp_mock/profile'
  _globals['_PROFILE']._serialized_start=24
  _globals['_PROFILE']._serialized_end=127
  _globals['_LIKE']._serialized_start=129
  _globals['_LIKE']._serialized_end=175
  _globals['_PROFILEREQUEST']._serialized_start=177
  _globals['_PROFILEREQUEST']._serialized_end=226
  _globals['_IDREQUEST']._serialized_start=228
  _globals['_IDREQUEST']._serialized_end=251
  _globals['_TARGETREQUEST']._serialized_start=253
  _globals['_TARGETREQUEST']._serialized_end=295
  _globals['_ERRORRESPONSE']._serialized_start=297
  _globals['_ERRORRESPONSE']._serialized_end=335
  _globals['_LIKESRESPONSE']._serialized_start=337
  _globals['_LIKESRESPONSE']._serialized_end=380
  _globals['_EMPTY']._serialized_start=382
  _globals['_EMPTY']._serialized_end=389
  _globals['_PROFILESERVICE']._serialized_start=392
  _globals['_PROFILESERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
