GRPC localhost:50051/proto.ProfileService/CreateProfile


{
  "profile": {
    "ID": 423425,
    "name": "John Doe",
    "age": 17,
    "description": "Love Kiyv<3",
    "location": "Киев"
  }
}


//{
//  "id": 423425
//}